version: "3.9"

services:
  frontend:
    container_name: smartvalidity-frontend
    build: .
    image: smartvalidity-frontend:latest
    ports:
      - "8081:80"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    external: true
